
[build]
  command = "npm ci && npm install terser && npm run build"
  publish = "dist"
  # Add environment variables that might help with the build
  environment = { NODE_VERSION = "20", NPM_FLAGS = "--no-optional --no-audit --prefer-offline" }

# The following redirect rule ensures that all routes are directed to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Improve security headers with proper SSL configuration
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; connect-src 'self' https://*.supabase.co https://api.openai.com;"

# Force HTTPS - Direct HTTP to HTTPS redirects
[[redirects]]
  from = "http://mealmaple.tech/*"
  to = "https://www.mealmaple.tech/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.mealmaple.tech/*"
  to = "https://www.mealmaple.tech/:splat"
  status = 301
  force = true

# Redirect naked domain to www
[[redirects]]
  from = "https://mealmaple.tech/*"
  to = "https://www.mealmaple.tech/:splat"
  status = 301
  force = true

# These headers ensure proper MIME types for JavaScript files
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/*.json"
  [headers.values]
    Content-Type = "application/json"

# Enable HSTS preloading
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

# Custom domain configuration
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[build.environment]
  NODE_VERSION = "20"
