// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvujrievuzvermpymirt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2dWpyaWV2dXp2ZXJtcHltaXJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2NzI0MTYsImV4cCI6MjA1NjI0ODQxNn0.vSnhm5yHufSYhPTSf6WMoFvs_OBsdV-Kffhl1IeSg8c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);